// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hztfkwtraqtvnwngvhwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6dGZrd3RyYXF0dm53bmd2aHdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzQ1NTAsImV4cCI6MjA3MDA1MDU1MH0.RQLXAzOx0pFj1qCn-QXMeJea8WQW6hBcfouwQoSCvlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});